a = float(input("Introduce el valor de a: "))
b = float(input("Introduce el valor de b: "))
c = float(input("Introduce el valor de c: "))
resultado = (a ** 3 * (b ** 2 - 2 * a * c )) / (2 * b)
print(f"El resultado es: {resultado}")